<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>name</key>
	<string>Regular Expression Replacement</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#escapes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#variables</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>escapes</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\[LUE]</string>
					<key>name</key>
					<string>keyword.operator.case-conversion.regexp-replace</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\[fnrt]</string>
					<key>name</key>
					<string>constant.character.escape.regexp-replace</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\x([a-f0-9]{2}|\{[a-f0-9]{4}\})</string>
					<key>name</key>
					<string>constant.character.escape.regexp-replace</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.regexp-replace</string>
				</dict>
			</array>
		</dict>
		<key>variables</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\$\$</string>
					<key>name</key>
					<string>constant.character.escape.regexp-replace</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\$(?x)( \d+ | \{ \w+ \} )</string>
					<key>name</key>
					<string>variable.other.constant.capture-content.regexp-replace</string>
				</dict>
			</array>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.regexp-replace.pcre2</string>
</dict>
</plist>
