"$schema" = "https://raw.githubusercontent.com/martinring/tmlanguage/master/tmlanguage.json"
name = "Regular Expression Replacement"
scopeName = "source.regexp-replace.pcre2"
patterns = [
    {include = "#escapes"},
    {include = "#variables"},
]

# TODO: Add conditional replacement - ${1:+foo:bar}

repository.escapes.patterns = [
    {match = '\\[LUE]', name = "keyword.operator.case-conversion.regexp-replace"},
    {match = '\\[fnrt]', name = "constant.character.escape.regexp-replace"},
    {match = '\\x([a-f0-9]{2}|\{[a-f0-9]{4}\})', name = "constant.character.escape.regexp-replace"},
    {match = '\\.', name = "constant.character.escape.regexp-replace"},
]

repository.variables.patterns = [
    {match = '\$\$', name = "constant.character.escape.regexp-replace"},
    {match = '\$(?x)( \d+ | \{ \w+ \} )', name = "variable.other.constant.capture-content.regexp-replace"},
]